# Generated by Django 4.0.1 on 2022-01-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikedby',
            name='liked',
        ),
    ]
