# Generated by Django 3.2.5 on 2022-01-11 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20220111_0532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlikedby',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='postlikedby',
            name='liked',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='postlikedby',
            unique_together={('post', 'liked_by')},
        ),
    ]
