# Generated by Django 3.2.5 on 2022-01-11 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20220111_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentonpost',
            options={'managed': True},
        ),
        migrations.AlterUniqueTogether(
            name='commentonpost',
            unique_together={('post', 'commented_by')},
        ),
    ]
