# Generated by Django 3.2.5 on 2022-01-11 07:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20220111_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentonpost',
            unique_together={('post', 'comment', 'commented_by')},
        ),
    ]
