# Generated by Django 3.2.5 on 2022-01-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_commentonpost_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentonpost',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='commentonpost',
            unique_together=set(),
        ),
    ]
